language: node_js
node_js:
  - 0.8
before_script: 
  - npm install -g grunt-cli
branches:
  only:
    - master
    - 1.3-stable
env:
  - JQUERIES=1.8.3
  - JQUERIES=1.10.1
  - JQUERIES=2.0.2
  - JQUERIES=git
notifications:
  irc:
    channels:
      - "chat.freenode.net#jquerymobile-dev"
