language: php

php:
  - "5.5"

sudo: false

cache:
  directories:
  - node_modules

before_script: 
  - npm install -g grunt-cli
  - npm install

script: npm run-script ci

env:
  - JQUERIES=1.8.3
    CITYPE=test
    SUITES=-navigation/sequence/sequence-dialog-hash-key-tests.html,-navigation/sequence/sequence-push-state-disabled-path1-path2-dialog-hash-key-tests.html,-navigation/sequence/sequence-path1-path2-dialog-hash-key-tests.html
  - JQUERIES=1.11.1
    CITYPE=test
    SUITES=-navigation/sequence/sequence-dialog-hash-key-tests.html,-navigation/sequence/sequence-push-state-disabled-path1-path2-dialog-hash-key-tests.html,-navigation/sequence/sequence-path1-path2-dialog-hash-key-tests.html
  - JQUERIES=2.1.1
    CITYPE=test
    SUITES=-navigation/sequence/sequence-dialog-hash-key-tests.html,-navigation/sequence/sequence-push-state-disabled-path1-path2-dialog-hash-key-tests.html,-navigation/sequence/sequence-path1-path2-dialog-hash-key-tests.html
  - JQUERIES=git
    CITYPE=test
    SUITES=-navigation/sequence/sequence-dialog-hash-key-tests.html,-navigation/sequence/sequence-push-state-disabled-path1-path2-dialog-hash-key-tests.html,-navigation/sequence/sequence-path1-path2-dialog-hash-key-tests.html
  - CITYPE=demos

notifications:
  irc:
    channels:
      - "chat.freenode.net#jqueryui-dev"
